# Generated by Django 6.0.2 on 2026-02-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.TextField(),
        ),
    ]
