# Generated by Django 6.0.2 on 2026-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_userprofile_role_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='picture',
            field=models.ImageField(null=True, upload_to='brands', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='picture',
            field=models.ImageField(null=True, upload_to='dealers', verbose_name='Image'),
        ),
    ]
