# Generated by Django 6.0.2 on 2026-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='cars', verbose_name='Image'),
        ),
    ]
