# Generated by Django 6.0.2 on 2026-04-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
