# Generated by Django 6.0.2 on 2026-04-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_car_user_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='picture',
            field=models.ImageField(null=True, upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(null=True, upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='picture',
            field=models.ImageField(null=True, upload_to='dealers'),
        ),
    ]
