# Generated by Django 6.0.2 on 2026-05-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_customer_name_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dealers'),
        ),
    ]
